.SUFFIXES:

ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment. export DEVKITPPC=<path to>devkitPPC")
endif

include $(DEVKITPPC)/wii_rules

TARGET		:=	neocd-rx_wii
TARGETDIR   :=  executables
BUILD		:=	build_wii
SOURCES		:=	src/fileio src src/cdaudio src/cdrom src/z80i \
				src/memory src/pd4990a src/cpu src/input src/video \
				src/mcard src/sound \
				src/fileio/chdlib/src src/fileio/chdlib/lzma \
				src/fileio/chdlib/zstd/common src/fileio/chdlib/zstd/decompress
INCLUDES	:=	src/z80 src/m68000 $(SOURCES) \
				src/fileio/chdlib/include src/fileio/chdlib/lzma \
				src/fileio/chdlib/zstd

CFLAGS		= -O3 -fomit-frame-pointer -mrvl -Wall -Wno-strict-aliasing $(MACHDEP) $(INCLUDE) -DHW_RVL \
			  -DTHREADED_AUDIO -DHAVE_ZLIB -DZ7_ST -DHAVE_FLAC -DZSTD_DISABLE_ASM
CXXFLAGS	= $(CFLAGS)
LDFLAGS		= $(MACHDEP) -Wl,-Map,$(notdir $@).map

LIBS	:=	-ldi -lfat -liso9660 -lwiiuse -lbte -logc -lm -lz -lmad -L ./../build_cpu -lz80 -lmc68000

LIBDIRS	:= $(PORTLIBS)

ifneq ($(BUILD),$(notdir $(CURDIR)))

export OUTPUT	:=	$(CURDIR)/$(TARGET)
export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
					$(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR	:=	$(CURDIR)/$(BUILD)

CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
sFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.S)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

export OFILES	:=	$(addsuffix .o,$(BINFILES)) \
			$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) \
			$(sFILES:.s=.o) $(SFILES:.S=.o)

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
			$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
			-I$(CURDIR)/$(BUILD) \
			-I$(LIBOGC_INC)

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib) \
					-L$(LIBOGC_LIB)

export OUTPUT	:=	$(CURDIR)/$(TARGETDIR)/$(TARGET)
.PHONY: $(BUILD) clean cpus cpus-clean

$(BUILD):
	@if test -d build_cpus; then echo ""; else [ -d $@ ] || mkdir -p build_cpu; cd src/m68000 && $(MAKE);cd ..; cd ..; cd src/z80 && $(MAKE); fi
	@[ -d $@ ] || mkdir -p $@
	@echo ""
	@echo "*** NeoCD RX Wii ******************************************************"
	@[ -d $(TARGETDIR) ] || mkdir -p $(TARGETDIR)
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.wii
	@echo "*************************************************************** Yay! \\o/ ***"

clean:
	@echo clean wii...
	@rm -fr $(BUILD) $(OUTPUT).elf $(OUTPUT).dol

cpus:
	@[ -d $@ ] || mkdir -p build_cpu
	@cd src/m68000 && $(MAKE)
	@cd src/z80 && $(MAKE)

cpus-clean:
	@rm -fr build_cpu

all: cpus $(BUILD)

clean-all: clean cpus-clean

run:
	dolphin-emu -e $(OUTPUT).elf

run-dol:
	$(DEVKITPRO)/emulators/gcube/gcube $(OUTPUT).dol

else

DEPENDS	:=	$(OFILES:.o=.d)

$(OUTPUT).dol: $(OUTPUT).elf
$(OUTPUT).elf: $(OFILES)

endif
