/****************************************************************************
*   NeoCDRX
*   NeoGeo CD Emulator
*   NeoCD Redux - Copyright (C) 2007 softdev
****************************************************************************/

#include "neocdrx.h"
#include "streams.h"
#include "eq.h"
#include <stdio.h>

/**
 * Nintendo Gamecube Audio Interface 
 */

u8 soundbuffer[2][8192] ATTRIBUTE_ALIGN(32);
u32 mixbuffer;
u32 audioStarted;
static int whichab = 0;
static int IsPlaying = 0;

#define AUDIO_DMA_FRAMES   800
#define AUDIO_DMA_BYTES    (AUDIO_DMA_FRAMES * 4)
#define AUDIO_START_FRAMES 2400

/****************************************************************************
 * AudioSwitchBuffers
 *
 * Genesis Plus only provides sound data on completion of each frame.
 * To try to make the audio less choppy, this function is called from both the
 * DMA completion and update_audio.
 *
 * Testing for data in the buffer ensures that there are no clashes.
 ****************************************************************************/
/*
 * Historical ~50 ms safety reserve.
 *
 * 2400 stereo frames at 48 kHz = 50 ms.  The CD Player already used this
 * margin successfully to absorb occasional GUI/input scheduling stalls.
 * Use the same reserve before starting the common Wii AI DMA path so BIOS,
 * YM2610 and CDDA all begin with the same jitter tolerance.
 */

static void AudioSwitchBuffers(void)
{
    int len;

    whichab ^= 1;

    /*
     * One fixed 800-frame DMA block.
     * This matches the 800 stereo frames generated by mixer_update_audio()
     * on each emulated video frame and avoids callback cadence changing with
     * temporary queue depth.
     */
    len = mixer_getaudio(soundbuffer[whichab], AUDIO_DMA_BYTES);

    IsPlaying = 1;
    AUDIO_InitDMA((u32) soundbuffer[whichab], len);
    DCFlushRange(soundbuffer[whichab], len);
    AUDIO_StartDMA();
}

/****************************************************************************
 * InitGCAudio
 *
 * Stock code to set the DSP at 48Khz
 ****************************************************************************/
void InitGCAudio(void)
{
    AUDIO_Init(NULL);
    AUDIO_SetDSPSampleRate(AI_SAMPLERATE_48KHZ);
    AUDIO_RegisterDMACallback(AudioSwitchBuffers);
    memset(soundbuffer, 0, 8192);
    mixer_init();
}

/****************************************************************************
 * Current GUI/CD Player compatibility helpers.
 * Normal in-game audio remains the RX path.
 ****************************************************************************/
void audio_player_begin (void)
{
    AUDIO_StopDMA();
    IsPlaying = 0;
    mixer_init();
}

void audio_player_update (void)
{
    mixer_update_cdda_only();

    if (IsPlaying == 0 &&
        mixer_queued_frames() >= AUDIO_START_FRAMES) {
       AUDIO_StopDMA();
       AudioSwitchBuffers();
    }
}

int audio_player_queued_frames (void)
{
    return (int)mixer_queued_frames();
}

void audio_player_end (void)
{
    AUDIO_StopDMA();
    IsPlaying = 0;
    mixer_init();
}

void audio_vsync_sync(void)
{
    /* RX original has no VBL/AI phase servo. */
}

/****************************************************************************
 * NeoCD Audio Update
 *
 * This is called on each VBL to get the next frame of audio.
 *****************************************************************************/
void update_audio(void)
{
    mixer_update_audio();

    if (IsPlaying == 0 &&
        mixer_queued_frames() >= AUDIO_START_FRAMES) {
       AUDIO_StopDMA();
       AudioSwitchBuffers();
    }
}
